// За потребите на софтвер за евиденција на приходите остварени од вработените во одделот за продажба, да се дефинира класа QuarterlySales во која се чуваат бројот на продажби остварени во одреден квартал, приходот добиен од секоја продажба и бројот на кварталот.

// Потоа, да се дефинира друга класа SalesPerson за кој се чува име (string) и низа од квартали (точно 4). За класите да се имплементираат соодветните конструктори и методи за правилно извршување на програмата. Да се имплементираат следните барања:

// • Метод int sumSales(SalesPerson sp) кој ќе врати сума од сите приходи остварени од дадениот вработен во одделот за продажба во сите квартали.

// • Метод SalesPerson salesChampion(SalesPerson [] arr) кој за дадената низа од работници ќе го врати работникот со најголем остварен приход (од сите квартали).

// • Да се дополни main методот во кој ќе се иницијализира низа од вработени во одделот за продажба и квартали согласно влезните тест примери. Во првиот ред се чита број на вработени, а понатаму прво во еден ред се чита името, па за секој квартал во еден ред бројот на продажби, и во следниот ред приходот добиен од секоја од тие продажби.

// • На стандарден излез да се испечати низата од вработени во одделот за продажба со помош на методата void table(SalesPerson [] arr) која за низата од вработени ќе отпечати приказ во следниот формат (за простор при печатење се користат три празни места):

// /

// For the purpose of a software for keeping track of the revenue generated by employees in the sales department, define a QuarterlySales class that stores the number of sales, the revenue generated by each sale and the number of the quarter.

// Then define another SalesPerson class for which a name(string) and an array of quarterly sales (exactly 4) are stored. For the classes implement the appropriate constructors and methods for the correct execution of the program.

// Implement the following requirements:

// • Method `int sumSales(SalesPerson sp)' which will return sum of all the revenues in all quarters generated by the given worker.

// • Method `SalesPerson salesChampion(SalesPerson [] arr)' which for the given array of sales employees will return the worker with the most generated revenue (of all quarters)

// • Add the `main' method, which will initialize an array of sales persons and quarters according to the input test cases. The number of sales employees is read from input in the first line, and then for each employee the name is read in the first line, and then for each of the quarters for that employee in the first line we have the number of sales, and then in the next line the revenue generated by each of those sales.

// • On standard output, print the array of sales employees using the method `void table(SalesPerson [] arr)', which will print a display for the array of sales persons in the following format (three spaces are used for printing space):


import java.util.Arrays;
import java.util.Scanner;

class QuarterlySales {

    private int numOfSales;
    private int [] revenues;
    private int quarterNo;

    public QuarterlySales(int numOfSales, int[] revenues, int quarterNo) {
        this.numOfSales = numOfSales;
        this.revenues = revenues;
        this.quarterNo = quarterNo;
    }

    public int qSum(){
        int sum = 0;
        for (int i = 0; i < revenues.length; i++) {
            sum += revenues[i];
        }
        return sum;
    }
 public void print(){
            System.out.print(qSum()+"   ");
 }

    public int[] getRevenues() {
        return revenues;
    }

    @Override
    public String toString() {
        return "QuarterlySales{" +
                "numOfSales=" + numOfSales +
                ", revenues=" + Arrays.toString(revenues) +
                ", quarterNo=" + quarterNo +
                '}';
    }

}

class SalesPerson {

    private String name;
    private QuarterlySales [] quarters;

    public SalesPerson(String name, QuarterlySales[] quarters) {
        this.name = name;
        this.quarters = quarters;
    }

    public String getName() {
        return name;
    }

    public QuarterlySales[] getQuarters() {
        return quarters;
    }

    int sumSales(){
        int sum = 0;
        for (int i = 0; i < quarters.length; i++) {
            sum += quarters[i].qSum();
        }
        return sum;
    }
 public void print(){
        for (int i = 0; i < quarters.length; i++) {
            int s=0;
            quarters[i].print();
        }
     System.out.print(sumSales()+"   ");
 }

    @Override
    public String toString() {
        return "SalesPerson{" +
                "name='" + name + '\'' +
                ", quarters=" + Arrays.toString(quarters) +
                '}';
    }

}



public class Main {

    public static SalesPerson salesChampion(SalesPerson [] arr)
    {
        SalesPerson champion = null;
        int max = 0;
        for (int i = 1; i < arr.length; i++) {
            if (arr[i].sumSales()>max){
                max=arr[i].sumSales();
                champion=arr[i];
            }
        }
        return champion;
    }
    public static void table(SalesPerson [] arr)
    {
        System.out.println("SP   1   2   3   4   Total");

     for (int i = 0; i < arr.length; i++) {
         System.out.print(arr[i].getName()+"   ");
        arr[i].print();
      System.out.println();
     }

    }

    public static void main(String[] args) {

        int n;
        Scanner input = new Scanner(System.in);
        n = input.nextInt();
        SalesPerson [] arr = new SalesPerson[n];

        for(int i=0;i<n;i++)
        {
         String name = input.next();

         QuarterlySales[] qniza = new QuarterlySales[4];

         for (int j = 0; j < 4; j++) {
           int numOfSales = input.nextInt();
           int[] revenues = new int[numOfSales];
           for (int k = 0; k < numOfSales; k++) {
               revenues[k] = input.nextInt();
           }
             qniza[j]=new QuarterlySales(numOfSales,revenues,j+1);
         }
    arr[i]=new SalesPerson(name,qniza);
        }

        table(arr);
        System.out.println("");
        System.out.println("SALES CHAMPION: " + salesChampion(arr).getName());

    }
}
